# build for linux!

FROM node:20-bookworm

RUN apt-get update && apt-get upgrade -y

RUN mkdir /vulkan
WORKDIR /vulkan

RUN apt-get install -y libglm-dev cmake libxcb-dri3-0 libxcb-present0 libpciaccess0 \
    libpng-dev libxcb-keysyms1-dev libxcb-dri3-dev libx11-dev g++ gcc g++-multilib \
     libwayland-dev libxrandr-dev libxcb-randr0-dev libxcb-ewmh-dev \
    git python-is-python3 python3 bison libx11-xcb-dev liblz4-dev libzstd-dev python3-distutils \
    ocaml-core ninja-build pkg-config libxml2-dev wayland-protocols python3-jsonschema \
    qtbase5-dev libxcb-xinput0 libxcb-xinerama0 make xorg-dev libxi-dev libxxf86vm-dev \
    libxinerama-dev libxcursor-dev libglfw3 libglfw3-dev

RUN wget https://sdk.lunarg.com/sdk/download/1.3.250.1/linux/vulkansdk-linux-x86_64-1.3.250.1.tar.gz
RUN tar xf vulkansdk-linux-x86_64-1.3.250.1.tar.gz
